VERSION:
3.001

// Include file below is generated by C-Builder      
// and contains the variables declared as -          
// PARAMETERS, INPUTS, OUTPUTS . . .                 
#include "InputLayerLinear.h"


STATIC:

// -----------------------------------------------   
// Variables declared here may be used in both the   
// RAM: and CODE: sections below.                    
// -----------------------------------------------   
//    double dt;    
double W[24] = {0.03613403, -0.28362049, 0.45106854, -0.17822748, 0.28526714, -0.52905004, 
               0.2875867, -0.07640608, -0.34945213, 0.46358854, -0.26428874, -0.48393429, 
               -0.38218059, 0.23149284, 0.11721479, -0.34579033, 0.21584494, -0.40444638, 
               0.37066775, 0.27426191, 0.25927248, 0.32212581, 0.24819487, 0.26270709};

double b[6] = {0.0,0.0,0.0,0.0,0.0,0.0};

int N;
int n;
int Y;


// - E n d   o f   S T A T I C :   S e c t i o n -   

RAM_FUNCTIONS:

// -----------------------------------------------   
// This section should contain any 'c' functions     
// to be called from the RAM section (either         
// RAM_PASS1 or RAM_PASS2). Example:                 
//                                                   
// static double myFunction(double v1, double v2)    
// {                                                 
//     return(v1*v2);                                
// }                                                 
// -----------------------------------------------   

RAM:
n = numInputs + numOutputs;
N = numInputs;
Y = numOutputs;

// -----------------------------------------------   
// Place C code here which computes constants        
// required for the CODE: section below.  The C      
// code here is executed once, prior to the start    
// of the simulation case.                           
// -----------------------------------------------   
//    dt= getTimeStep();                             


// ------------- End of RAM: Section -------------   


CODE_FUNCTIONS:
double X[6] = {0.0,0.0,0.0,0.0,0.0,0.0};
double X1[6] = {0.0,0.0,0.0,0.0,0.0,0.0};
double X11[6] = {0.0,0.0,0.0,0.0,0.0,0.0};

double a1[6]; //output array

double loss[6] = {0.0,0.0,0.0,0.0,0.0,0.0};
int i;
int k;
int indx;

double L;


static void FeedForward(int Y){

for (k = 0; k<Y; k++){
	indx = 4*k;
	a1[k] = W[0+indx] * X[0]+ W[1+indx]*X[1] + W[2				+indx]*X[2] +W[3+indx]*X[3] + b[k]; 


}
}


static void Backprop(double Loss[6], int N, int Y, double alpha, double lamb){

for (k = 0; k<Y; k++){
	L = loss[k];
	b[k] = b[k] - L*alpha;
	
	for (i = 0; i<N; i++){ 
		W[4*k+i] = W[4*k+i] - L* alpha* X11[i]- lamb * ((W[4*k+i] > 0) - (W[4*k+i] < 0));
}
}
}

static void saveX(int N){
for (i = 0; i<N; i++){ 

X11[i] = X1[i];
X1[i] = X[i];
}
}


CODE:

if (Learning_rate>0.0){

loss[0] = L1;
if (Y>1){
	loss[1] = L2;
	if (Y>2){
		loss[2] = L3;
		if (Y>3){
			loss[3] = L4;
			if (Y>4){
				loss[4] = L5;
				if (Y>5){
					loss[5] = L6;

				}
			}
		}
	}
	
}

Backprop(loss, N, Y, Learning_rate,lamm);


}

saveX(N);

X[0] = input1;
if (N>1){
	X[1] = input2;
	if (N>2){
		X[2] = input3;
		if (N>3){
			X[3] = input4;
		}
	}
	
}

FeedForward(Y);

foutput = a1[0];
foutput2 = a1[1];
foutput3 = a1[2];
foutput4 = a1[3];
foutput5 = a1[4];
foutput6 = a1[5];





// -----------------------------------------------   
// Place C code here which runs on the RTDS. The     
// code below is entered once each simulation        
// step.                                             
// -----------------------------------------------   


// ------------ End of CODE: Section -------------   

