VERSION:
3.001

// Include file below is generated by C-Builder      
// and contains the variables declared as -          
// PARAMETERS, INPUTS, OUTPUTS . . .                 
#include "MidLayerLinear.h"


STATIC:

// -----------------------------------------------   
// Variables declared here may be used in both the   
// RAM: and CODE: sections below.                    
// -----------------------------------------------   
//    double dt;    

double W[36]= {-0.33688728, 0.04074035, -0.01483526, -0.22810301, -0.06549792, 0.12533253, 
               0.29282514, -0.4411586, 0.24198634, 0.09089853, -0.37128312, 0.40662572, 
               -0.33032561, 0.10374387, 0.47703259, -0.11751871, 0.02011849, 0.05374809, 
               0.31882578, 0.06420085, -0.16702248, -0.0172307, -0.36629948, -0.06796555, 
               0.36483984, -0.39621302, -0.10038296, 0.15220206, 0.02337343, 0.19608224, 
               0.07071909, 0.01232094, 0.06939054, 0.22498936, 0.07068917, 0.10866029};;
double b[6] = {0.0,0.0,0.0,0.0,0.0,0.0};
int N;
int n;
int Y;
// - E n d   o f   S T A T I C :   S e c t i o n -   

RAM_FUNCTIONS:


// -----------------------------------------------   
// This section should contain any 'c' functions     
// to be called from the RAM section (either         
// RAM_PASS1 or RAM_PASS2). Example:                 
//                                                   
// static double myFunction(double v1, double v2)    
// {                                                 
//     return(v1*v2);                                
// }                                                 
// -----------------------------------------------   

RAM:
n = numInputs + numOutputs;
N = numInputs;
Y = numOutputs;
// -----------------------------------------------   
// Place C code here which computes constants        
// required for the CODE: section below.  The C      
// code here is executed once, prior to the start    
// of the simulation case.                           
// -----------------------------------------------   
//    dt= getTimeStep();                             


// ------------- End of RAM: Section -------------   


CODE_FUNCTIONS:
double X[6] = {0.0,0.0,0.0,0.0,0.0,0.0};
double X1[6] = {0.0,0.0,0.0,0.0,0.0,0.0};
double X11[6] = {0.0,0.0,0.0,0.0,0.0,0.0};

double a2[6]; //output array
double da1[6];
double da[6];

//double a22[6]={0.0,0.0,0.0,0.0,0.0,0.0}; 
int i;
int k;
int indx;
//double dW[36];
double loss[6] = {0.0,0.0,0.0,0.0,0.0,0.0};
double L;


int rec = 0;
int sent = 0;



static void FeedForward(int Y){

for (k = 0; k<Y; k++){
indx = 6*k;
a2[k] = W[0+indx]*X[0] + W[1+indx]*X[1] + W[2+indx]*X[2] +W[3+indx]*X[3] +W[4+indx]*X[4] + W[5+indx]*X[5] + b[k];

}
}



static void Backprop(double Loss[6], int N, int Y, double alpha, double lambda){
da1[0] = 0.0;
da1[1] = 0.0;
da1[2] = 0.0;
da1[3] = 0.0;
da1[4] = 0.0;
da1[5] = 0.0;

for (k = 0; k<Y; k++){
	L = loss[k]; 
	b[k] = b[k] - L*alpha;

	for (i = 0; i<N; i++){
		W[6*k+i] = W[6*k+i] - L* alpha* X1[i]- lambda * ((W[6*k+i] > 0) - (W[6*k+i] < 0));;
		da1[i] += L * W[i*k];
	}


}

}


static void saveX(int N){
for (i = 0; i<N; i++){ 
X1[i] = X[i];
}
}



CODE:

if (Learning_rate>0.0){

loss[0] = L1;
if (Y>1){
	loss[1] = L2;
	if (Y>2){
		loss[2] = L3;
		if (Y>3){
			loss[3] = L4;
			if (Y>4){
				loss[4] = L5;
				if (Y>5){
					loss[5] = L6;

				}
			}
		}
	}
	
}


Backprop(loss, N, Y, Learning_rate, lamm);


Li1 = da1[0];
Li2 = da1[1];
Li3 = da1[2];
Li4 = da1[3];
Li5 = da1[4];
Li6 = da1[5];


}

saveX(N);

X[0] = input1;
if (N>1){
	X[1] = input2;
	if (N>2){
		X[2] = input3;
		if (N>3){
			X[3] = input4;
			if (N>4){
				X[4] = input5;
				if (N>5){
					X[5] = input6;

				}
			}
		}
	}
	
}

FeedForward(Y);

foutput = a2[0];
foutput2 = a2[1];
foutput3 = a2[2];
foutput4 = a2[3];
foutput5 = a2[4];
foutput6 = a2[5];


// -----------------------------------------------   
// Place C code here which runs on the RTDS. The     
// code below is entered once each simulation        
// step.                                             
// -----------------------------------------------   


// ------------ End of CODE: Section -------------   

