VERSION:
3.001

// Include file below is generated by C-Builder      
// and contains the variables declared as -          
// PARAMETERS, INPUTS, OUTPUTS . . .                 
#include "OutputLayerLinear.h"


STATIC:

// -----------------------------------------------   
// Variables declared here may be used in both the   
// RAM: and CODE: sections below.                    
// -----------------------------------------------   
//    double dt;    

double W[12]={-0.082978, 0.22032449, -0.49988563, -0.19766743, -0.35324411, -0.40766141, -0.31373979, -0.15443927, -0.10323253, 0.03881673, -0.08080549, 0.1852195};
double b[2] = {0.0,0.0};
int n;
int N;
int dt = 0;

double dLoss_dW;
double dLoss_dW2;

// - E n d   o f   S T A T I C :   S e c t i o n -   

RAM_FUNCTIONS:

// -----------------------------------------------   
// This section should contain any 'c' functions     
// to be called from the RAM section (either         
// RAM_PASS1 or RAM_PASS2). Example:                 
//                                                   
// static double myFunction(double v1, double v2)    
// {                                                 
//     return(v1*v2);                                
// }                                                 
// -----------------------------------------------   

RAM:
n = numInputs + numOutputs;
N = numInputs;
// -----------------------------------------------   
// Place C code here which computes constants        
// required for the CODE: section below.  The C      
// code here is executed once, prior to the start    
// of the simulation case.                           
// -----------------------------------------------   
//    dt= getTimeStep();                             


// ------------- End of RAM: Section -------------   


CODE_FUNCTIONS:

double preOutput = 0;
double preOutput2 = 0;
double tmp;
int i;
int k;
double out1;
double out2;
//static void MatrixMult(double X[N], double Y){}

double X[6];
double X1[6] = {0.0,0.0,0.0,0.0,0.0,0.0};
double dLoss_da2[6];

int rec = 0;
int sent = 0;
int waitt = 0;

double lossy1;
double lossy2;

static void FeedForward(int N){

preOutput = 0.0;
preOutput2 = 0.0;

for (i = 0; i < N; i++){

preOutput += W[i] * X[i];
preOutput2 += W[i+N] * X[i];
}

out1 = preOutput + b[0];
out2 = preOutput2 + b[1];

}

static void Backprop(double loss, double loss2, int N, double alpha, double lambda){

for (i = 0; i < N; i++){

dLoss_da2[i] = loss *W[i] + loss2 *W[i+N];

dLoss_dW = loss *X[i];
dLoss_dW2 = loss2 *X[i];
W[i] = W[i] - alpha * dLoss_dW - lambda * ((W[i] > 0) - (W[i] < 0));
W[i+N] = W[i+N] - alpha * dLoss_dW2- lambda * ((W[i+N] > 0) - (W[i+N] < 0));

}
b[0] = b[0] - alpha * loss;
b[1] = b[1] - alpha * loss2;
}

static void saveX(int N){
for (i = 0; i<N; i++){ 
X1[i] = X[i];
}
}



CODE:


if (Learning_rate>0.0){

Backprop(label, label2, N, Learning_rate, lam);

Li1 = dLoss_da2[0];
if (N>1){		//Maybe remove ifs and initiate array with zeros
	Li2 = dLoss_da2[1];
	if (N>2){
		Li3 = dLoss_da2[2];
		if (N>3){
			Li4 = dLoss_da2[3];
			if (N>4){
				Li5 = dLoss_da2[4];
				if (N>5){
					Li6 = dLoss_da2[5];

				}
			}
		}
	}
	
}

	

}


//Maybe remove all if statements
X[0] = input1;
if (N>1){
	X[1] = input2;
	if (N>2){
		X[2] = input3;
		if (N>3){
			X[3] = input4;
			if (N>4){
				X[4] = input5;
				if (N>5){
					X[5] = input6;

				}
			}
		}
	}
	
}

FeedForward(N);
foutput = out1;
foutput2 = out2;

// -----------------------------------------------   
// Place C code here which runs on the RTDS. The     
// code below is entered once each simulation        
// step.                                             
// -----------------------------------------------   


// ------------ End of CODE: Section -------------   
