/* DO NOT EDIT THIS FILE */

MODEL_TYPE: CTL

#define PI        3.1415926535897932384626433832795
#define TWOPI     6.283185307179586476925286766559
#define E         2.71828182845904523536028747135266
#define EINV      0.36787944117144232159552377016147
#define RT2       1.4142135623730950488016887242097
#define RT3       1.7320508075688772935274463415059
#define INV_ROOT2 0.70710678118654752440084436210485

INPUTS:
  double Learning_rate;
  double lamm;
  double x1;
  double x2;
  double x3;
  double x4;
  double x5;
  double x6;
  double x7;
  double x8;
  double x9;
  double x10;
  double L1;
  double L2;
  double L3;
  double L4;
  double L5;
  double L6;
  double L7;
  double L8;
  double L9;
  double L10;

OUTPUTS:
  double foutput;
  double foutput2;
  double foutput3;
  double foutput4;
  double foutput5;
  double foutput6;
  double foutput7;
  double foutput8;
  double foutput9;
  double foutput10;
  double tests;

PARAMETERS:
  int numInputs;
  int numOutputs;
  int Layers;
  int batch_size;
  int activation1;
  int Nodes1;
  int activation2;
  int Nodes2;
  int activation3;
  int Nodes3;