/* DO NOT EDIT THIS FILE */

MODEL_TYPE: CTL

#define PI        3.1415926535897932384626433832795   // definition of PI                 
#define TWOPI     6.283185307179586476925286766559    // definition of 2.0*PI             
#define E         2.71828182845904523536028747135266  // definition of E                  
#define EINV      0.36787944117144232159552377016147  // definition of E Inverse (1/E)    
#define RT2       1.4142135623730950488016887242097   // definition of square root 2.0    
#define RT3       1.7320508075688772935274463415059   // definition of square root 3.0    
#define INV_ROOT2 0.70710678118654752440084436210485                                      

INPUTS:
  double input1;
  double input2;
  double input3;
  double input4;
  double label;
  double Learning_rate;

OUTPUTS:
  double foutput;

PARAMETERS:
  int numInputs;  //Description
  int type;       //Description
  int numLayers;  //Description
  int numNodes;   //Description
  int numWeights; //Description

